log_level = <LOGGER LEVEL>
token = <TOKEN>
chat_id = <CHAT ID>
bot_log_level = <LOG LEVEL>
access_users = [...]

[messages]
unknown =
first_massage =
wrong_link =
error =

[scraper]
medium = "medium"
website =
login =
password =
api =
